### ISSUE TITLE
Feature request: Specify input and output files by ENV

### ISSUE THREAD

**Issue by mpfl** [djdembeck/bragibooks#253]
I have a single NFS share (media) with subfolders I'd like to use for input (audiobooks-raw) and output (audiobooks).

It would be great to be able to specify these input and output folders when spinning up the container for the first time, such as:

```yaml
services:
  bragi:
    ...
    volumes:
      media:/media
    environment:
      - INPUT=/media/audiobooks-raw
      - OUTPUT=/media/audiobooks
    ...

volumes:
  media:
    external: true
```
