### ISSUE TITLE
[bug] docker nun running up

### ISSUE THREAD

**Issue by 9Mad-Max5** [djdembeck/bragibooks#50]
Hi,

I just saw your docker and tried to run it.
Unfortunately, it immediately drops this error.

```
Attaching to bragibooks
bragibooks    | Traceback (most recent call last):
bragibooks    |   File "/home/app/web/manage.py", line 23, in <module>
bragibooks    |     f = open(SECRET_PATH, "w")
bragibooks    | PermissionError: [Errno 13] Permission denied: '/config/secret_key.txt'
bragibooks exited with code 1
```

compose:
```
version: '3.7'
services:
  bragibooks:
    image: ghcr.io/djdembeck/bragibooks:main
    container_name: bragibooks
    volumes:
      - $DOCKERDIR/bragibooks/config:/config
      - $MEDIADIR/Audiobook_Correction/input:/input
      - $MEDIADIR/Audiobook_Correction/output:/output
    environment:
      - LOG_LEVEL: ERROR
    networks:
      - traefik
```
